### PR TITLE
Move ssh commands to scripts on bare metal server

### PR DESCRIPTION
**Pull request by bmarkons**
We are currently executing commands for running benchmarks one by one from [RemoteServerJob](https://github.com/ruby-bench/ruby-bench-web/blob/master/app/jobs/remote_server_job.rb). I moved those to scripts which would be placed on server and called from [RemoteServerJob](https://github.com/ruby-bench/ruby-bench-web/blob/master/app/jobs/remote_server_job.rb).

Primarily I did this because I want to log if any error from running those commands. If you take a look at one of scripts you'll notice output redirected with `exec &>> file/to/log`. It would help us with debugging errors. I did this after trying to find out why rails benchmarks aren't run.

What do you think @robin850? :)

### CODE REVIEW

**Comment by robin850** [comment]
Hey Marko !

That's a pretty good idea for debugging purpose to give the ability to run these tasks. The only tiny problem I'm seeing is that there is a lot of duplicate. There's a clear pattern though:

* Redirect outputs to the log file.
* Several `echo`s with the date.
* Do the docker dance (pull, start PG / MySQL / Redis, run, ...).
* (Optional) `docker stop` + `docker rm`.

Maybe you could try to share things between the different scripts (this may be pretty interesting for scripts running PostgreSQL, MySQL and Redis as they include the version number). What do you think ?

**Comment by tgxworld** [comment]
@bmarkons I don;t know about this. Maybe add the runner scripts to `ruby-bench-docker` and just clone the repository onto the bare metal server? `ruby-bench-server` feels like the wrong repository to me.

**Comment by bmarkons** [comment]
@tgxworld I had some time thinking where should I place those scripts but this repo seemed like best fit.

I guess we could simply clone this one when setting up new server and run setup script, while having running scripts cloned at the same time. 

Does it make sense? I can move them in docker repo though I find this one more suitable. Am I missing something?

**Comment by tgxworld** [comment]
ruby-bench-server is only meant to hold scripts that would bootstrap a new bare metal server by installing services we need like Docker.

**Pull request closed without merging**
