### PR TITLE
Add setup script for servers.

### PR DESCRIPTION
**Pull request by tgxworld**
@SamSaffron Could you have a look at this?

### CODE REVIEW

**Comment by SamSaffron** [comment]
This sound about right, can you test it works as expected using i7z while running the bench https://code.google.com/p/i7z/ cpu speed should remain stable and consistent.

**Comment by tgxworld** [comment]
@SamSaffron From i7z, it seems like it still isn't being configured correctly right now? I followed https://wiki.archlinux.org/index.php/CPU_frequency_scaling to configure the server.

`Top right terminal:  watch grep \"cpu MHz\" /proc/cpuinfo`
screenshot from 2015-01-30 09 24 54

`cpufreq-info`

screenshot from 2015-01-30 09 25 33

**Comment by SamSaffron** [comment]
that looks more or less right but can't you set the governor to performance? that is usually what I would do, cpufrequtil allows you to do that

**Comment by tgxworld** [comment]
Any concerns with Turbo Boost being enabled?

> but can't you set the governor to performance?

~~I could but wouldn't it be better to set it to a fixed frequency? From my understanding, the performance governor will run at the maximum(the maximum might change from time to time) possible frequency at that instance?~~

**Comment by tgxworld** [comment]
@SamSaffron  Opps ignore my previous comment. Seems like setting it to performance will result in more or less the same thing.

screenshot from 2015-01-30 16 16 05

Do we still need to disable `TURBO` though?

**Comment by kirs** [comment]
What about using Chef/Puppet for such tasks?

**Comment by tgxworld** [comment]
@kirs  I'm open to those too but I've not had experience with any of them. I think it is time I look into both :)

**Comment by kirs** [comment]
You can also try Ansible (it's the easiest one)

**Comment by tgxworld** [comment]
Merging this in to resetup the server.

**Pull request merged**
